sudo : required
service:
  - docker

before_install:
  - docker build -t dockeramol17/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dockeramol17/docker-react npm run test -- --coverage --watchAll=false